import Head from "next/head";
import { Inter } from "next/font/google";

import { Login } from "@/components";
import { Container, Heading } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading>Welcome to your page.</Heading>
      </main>
    </>
  );
}
