import Head from "next/head";
import { Inter } from "next/font/google";

import { Login } from "@/components";
import { Button, Center, Container, Heading } from "@chakra-ui/react";
import { useAuthCheck } from "@/utils/hooks";
import { clearLocalStorage, pb } from "@/utils";
import { useRouter } from "next/router";
import NoSSR from "react-no-ssr";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useAuthCheck();
  const route = useRouter();

  return (
    <NoSSR>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading>Welcome to your page.</Heading>
        <Center my="5">
          <Button
            onClick={() => {
              clearLocalStorage();
              route.push("/login");
            }}
            colorScheme="red"
          >
            Logout
          </Button>
        </Center>
      </main>
    </NoSSR>
  );
}
